version: 2.1
orbs:
  node: circleci/node@1.1.6
  cypress: cypress-io/cypress@1

# jobs:
#   unit-test:
#     executor:
#       name: node/default
#     steps:
#       - checkout
#       - node/with-cache:
#           steps:
#             - run: npm install
#             - run: npm test

# workflows:
#   build-and-test:
#     jobs:
#       - unit-test
#       - cypress/run:
#         start: npm start
#         wait-on: "http://localhost:3000"

workflows:
  build:
    jobs:
      - cypress/run:
          start: npm start
          wait-on: "http://localhost:3000"
