version: 2.1
orbs:
  node: circleci/node@1.1.6
  cypress: cypress-io/cypress@1
jobs:
  unit-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  e2e-test:
    - cypress/run

workflows:
  build-and-test:
    jobs:
      - unit-test
      - e2e-test
